version: '3.9'

services:
  postgres:
    restart: always
    image: postgres:15.2-alpine3.17
    ports:
      - '5432:5432'
    container_name: local-app-db
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_DB=${POSTGRES_DB}'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./local-db/001.sql:/docker-entrypoint-initdb.d/001.sql